### ISSUE TITLE
Issue: Firebase Authentication Error: `auth/unauthorized-domain`

### ISSUE THREAD

**Issue by Isax03** [VesperAkshay/qr-code-generator#4] opened 2024-09-24 16:37 UTC
When trying to log in with Google, the site returns the following error:
>    ```
>    Error: auth/unauthorized-domain
> ```
---
Steps to reproduce:
1. Go to the login page: [https://quick-qr-builder.vercel.app/login](https://quick-qr-builder.vercel.app/login).
2. Click the "Sign in with Google" button.

Expected result:
- The user should be able to log in using their Google account.

Actual result:
- The login process fails with the error: `auth/unauthorized-domain`.

It seems that the domain might not be correctly added to the authorized domains list in the Firebase console.

**Comment by adilkadivala** [comment] 2024-09-25 01:52
hey @Isax03 

 let me assign this isssue

**Comment by adilkadivala** [comment] 2024-09-25 02:31
register  with google is also not working 


error


Google Sign-In Error: Firebase: Error (auth/configuration-not-found).

**Comment by Isax03** [comment] 2024-09-25 04:52
Sure, but you need access to the firebase console

**Comment by VesperAkshay** [comment] 2024-09-25 06:33
The Issue is resolved 

We just have to add the deployment domain 

Thanks for pointing out the mistake

**Closed** 2024-09-25 10:09 UTC
Labels: good first issue
